# Generated by Django 3.2 on 2024-12-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20241224_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=128, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
