# Generated by Django 3.2 on 2024-12-30 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_unique_review'),
        ('reviews', '0006_auto_20241227_0948'),
    ]

    operations = [
    ]
