# Generated by Django 3.2 on 2025-01-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_merge_20250103_1342'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='один отзыв на 1 произведение',
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
        migrations.AlterUniqueTogether(
            name='titlegenre',
            unique_together=set(),
        ),
    ]
