# Generated by Django 3.2 on 2025-01-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_merge_20241230_1643'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='один отзыв на 1 произведение',
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Год'),
        ),
        migrations.AlterUniqueTogether(
            name='titlegenre',
            unique_together=set(),
        ),
    ]
